### ISSUE TITLE
 the code for the test part

### ISSUE THREAD

**Issue by feiniujuan** [iantsen/hecktor#2]
Hello, I am using your innovation to learn how to segment the head and neck tumor. Your innovation is great and gave me a lot of inspiration, but I encountered difficulties in the test part. Can I get the code for your test part? Thank you very much! I am very sorry for any offense.

**Comment by iantsen** [comment]
Hello! I am glad that you are interested in this work. I have uploaded the code for model inference as well as the weights of the pretrained models so that you could reproduce all results from the paper. You can find more information in readme.

**Comment by feiniujuan** [comment]
Thank you very much! You helped me a lot
