### ISSUE TITLE
Model weights and splits

### ISSUE THREAD

**Issue by vokcow** [iantsen/hecktor#4]
Dear Andrei,

I would like to ask about the model weights and train-val splits. I see that the four "new splits" correspond to the random splits, where all centers are present, and the other four splits are the "leave one center out" splits.

I see that your model weights are named either `ns` and `s`. Could you please confirm if `ns` 
 correspond to the "new splits" (e.g. random splits), and `s` relates to the "leave on center out" splits? And could you please confirm if the ordering (0,1,2,3) of the splits is the same than the ordering of the model weights?

Many thanks in advance,

Víctor

**Comment by iantsen** [comment]
Hello @VokCow 

> I see that your model weights are named either ns and s. Could you please confirm if `ns` correspond to the "new splits" (e.g. random splits), and `s` relates to the "leave on center out" splits?

Yes, that is correct. I confirm.

> And could you please confirm if the ordering (0,1,2,3) of the splits is the same than the ordering of the model weights?

Yes, the order is the same. 

All splits are basically a dictionary with two keys ('train', 'val'), so that you can identify the part of patients used for training and validation, respectively.

**Comment by vokcow** [comment]
Hi Andrei, 

Thanks for confirming. I now close this issue.
Kind regards,

Víctor.
