### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 2405 (char 2404)

### ISSUE THREAD

**Issue by qiangliuhfut** [iantsen/hecktor#7]
![image](https://user-images.githubusercontent.com/50510851/133887503-0f70aee1-407d-4b4b-8594-03ee9cdb86cd.png)

During training, import the pkl file after dividing the patient-id, and there is an error in reading

**Comment by iantsen** [comment]
Hi! There is a problem with loading a pkl file with train - val splits. Do you use the original files located in `src/data/splits/`? The error is in the part:
```python
with open(path_to_train_val_pkl) as f:
        train_val_split = json.load(f)
```
Try to reproduce this piece of code with your pkl files to find the exact reason. `path_to_train_val_pkl` is the path to a pkl file with patients' names.

**Comment by qiangliuhfut** [comment]
Thanks for your reply！  I have solved the problem.      
Thanks again！

**Comment by qiangliuhfut** [comment]
> Hi! There is a problem with loading a pkl file with train - val splits. Do you use the original files located in `src/data/splits/`? The error is in the part:
> 
> ```python
> with open(path_to_train_val_pkl) as f:
>         train_val_split = json.load(f)
> ```
> 
> Try to reproduce this piece of code with your pkl files to find the exact reason. `path_to_train_val_pkl` is the path to a pkl file with patients' names.

Thanks for your reply！ I have solved the problem.
Thanks again！
